baseURL = "https://dahi.icu/"
languageCode = "zh-tw"
title = "Dahi"
theme = "kagome"
paginate = 15
copyright = "轉載請註明出處  © Dahi.icu"
hasCJKLanguage = true
googleAnalytics = 'G-PYKTMJEK97'

[author]
  name = "Dahi"
  email = "expect@dahi.icu"
  description = "Genshin, start."
  avatar = "https://coolapk-oss-image.oss-cn-hangzhou.aliyuncs.com/feed/2023/0721/16/999_09be2a00_6933_9634_588@1024x1024.png"
  

# 菜单/导航栏
[menu]
  # 顶部导航栏
  [[menu.main]]
    identifier = "/"
    name = "首頁"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "/posts"
    name = "文章"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "/dns"
    name = "DNS"
    url = "/dns"
    weight = 3
  [[menu.main]]
    identifier = "/link"
    name = "友人"
    url = "/link"
    weight = 4
  
  # 底部社交图标
  [[menu.social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/dahisea"
    weight = 1
  [[menu.social]]
    identifier = "telegram"
    name = "telegram"
    url = "https://t.me/dahi_no_chatbot"
    weight = 2
  [[menu.social]]
    identifier = "kuan"
    name = "kuan"
    url = "https://www.coolapk.com/u/1641832"
    weight = 3


# 主题相关配置项
[params]
  keywords = ['Dahi']
  description = "A blog."
  mainSections = ["posts"]
  # 国内备案号
  beian = "萌ICP备20213149号"
  # TOC目录出现字符长度限制
  toc_show_len = 300
  
  [params.widget]
    # 相关文章推荐数量
    articles_count = 6
    # 分类相关显示数量
    categories_count = 6
    # 标签相关显示数量
    tags_count = 12

