baseURL = "https://dahi.icu/"
languageCode = "zh-tw"
title = "Dahi"
theme = "kagome"
paginate = 7
copyright = "© Dahi."
hasCJKLanguage = true

# 作者信息
[author]
  name = "Dahi"
  email = "expect@dahi.icu"
  description = "Genshin, start."
  avatar = "https://coolapk-oss-image.oss-cn-hangzhou.aliyuncs.com/feed/2023/0711/07/1641832_ef9c1022_2726_318_968@1080x1080.png"

# 菜单/导航栏
[menu]
  # 顶部导航栏
  [[menu.main]]
    identifier = "/"
    name = "首頁"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "/posts"
    name = "文章"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "/dns"
    name = "DNS"
    url = "/dns"
    weight = 3
  [[menu.main]]
    identifier = "/link"
    name = "友人"
    url = "/link"
    weight = 4
  
  # 底部社交图标
  [[menu.social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/dahisea"
    weight = 1
  [[menu.social]]
    identifier = "kuan"
    name = "kuan"
    url = "https://www.coolapk.com/u/1641832"
    weight = 2


# 主题相关配置项
[params]
  keywords = ['']
  description = ""
  mainSections = ["posts"]
  # 国内备案号
  beian = ""
  # TOC目录出现字符长度限制
  toc_show_len = 300


  [params.widget]
    # 相关文章推荐数量
    articles_count = 6
    # 分类相关显示数量
    categories_count = 6
    # 标签相关显示数量
    tags_count = 12

  [params.aplayer]
    theme = "#b7daff"
    autoplay = false
    loop = "none"
    mutex = true

  [params.dplayer]
    theme = "#b7daff"
    autoplay = false
    loop = false
    mutex = true
